InsuranceCompany/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from InsuranceCompany.accounts.views import APIUserListView, APIUserDetailView
from InsuranceCompany.common.views import APICarListView, APICarDetailView, APIOfferListView, APIOfferDetailView
from InsuranceCompany.policies.views import APIPolicyListView, APIPolicyDetailView, APIDiscountListView, \
    APIDiscountDetailView, APIClaimListView, APIClaimDetailView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include([
        path('common/car/', APICarListView.as_view()),
        path('common/car/<int:pk>/', APICarDetailView.as_view()),
        path('common/offer/', APIOfferListView.as_view()),
        path('common/offer/<int:pk>/', APIOfferDetailView.as_view()),
        path('accounts/', APIUserListView.as_view()),
        path('accounts/<int:pk>/', APIUserDetailView.as_view()),
        path('policies/', APIPolicyListView.as_view()),
        path('policies/<int:pk>/', APIPolicyDetailView.as_view()),
        path('policies/discount/', APIDiscountListView.as_view()),
        path('policies/discount/<int:pk>/', APIDiscountDetailView.as_view()),
        path('policies/claim/', APIClaimListView.as_view()),
        path('policies/claim/<int:pk>/', APIClaimDetailView.as_view()),
    ])),
    path('', include('InsuranceCompany.common.urls')),
    path('accounts/', include('InsuranceCompany.accounts.urls')),
    path('policies/', include('InsuranceCompany.policies.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

InsuranceCompany/common/models.py
from decimal import Decimal

from django.conf import settings
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator
from django.db import models
from datetime import date

from InsuranceCompany.policies.models import Discount, InsurancePolicy


# Create your models here.

class Car(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='car_user')
    make = models.CharField(max_length=100)
    model = models.CharField(max_length=100)
    year = models.IntegerField()

    def __str__(self):
        return f"{self.make} {self.model} {self.year}"


class Offer(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Чакаща'),
        ('accepted', 'Приета'),
        ('rejected', 'Отхвърлена'),
    ]

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    insurance_amount = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        validators=[MinValueValidator(0)],
        verbose_name="Застрахователна сума"
    )
    discounts = models.ManyToManyField(Discount, blank=True, related_name="offers")
    premium = models.DecimalField(max_digits=10, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='pending',
        verbose_name="Статус"
    )
    related_name = 'offers'
    created_policy = models.OneToOneField(InsurancePolicy, on_delete=models.CASCADE, null=True,
                                          related_name='offer_to_policy')

    def accept(self):
        self.status = 'accepted'
        self.save()

    def reject(self):
        self.status = 'rejected'
        self.save()

    def __str__(self):
        return f"Оферта #{self.id} за {self.car} ({self.get_status_display()})"

InsuranceCompany/policies/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.conf import settings

from InsuranceCompany.accounts.models import Profile

# Create your models here.

import random


class InsurancePolicy(models.Model):
    policy_number = models.CharField(max_length=10, unique=True, editable=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    car = models.OneToOneField('common.Car', on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    is_active = models.BooleanField(default=True)
    insurance_amount = models.DecimalField(max_digits=10, decimal_places=2)
    offer = models.OneToOneField('common.Offer', on_delete=models.CASCADE, null=True)

    def save(self, *args, **kwargs):
        if not self.policy_number:
            self.policy_number = f"POL-{random.randint(100000, 999999)}"
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.policy_number}"

    def get_status_display(self):
        return "Активна" if self.is_active else "Неактивна"


class Discount(models.Model):
    DISCOUNT_TYPES = [
        ('NEW_CLIENT', 'нов клиент'),
        ('INSURANCE_AMOUNT', 'застрахователна сума над 10,000 лв.'),
        ('CAR_AGE', 'автомобил под 10г.'),
    ]

    discount_type = models.CharField(choices=DISCOUNT_TYPES, unique=True)
    percentage = models.IntegerField(
        validators=[
            MinValueValidator(1, message="Размерът на отстъпката не може да бъде по-малък от 1%"),
            MaxValueValidator(25, message="Размерът на отстъпката не може да бъде по-голям от 25%")
        ]
    )

    def __str__(self):
        return f" Отстъпка за {self.get_discount_type_display()}"

    def discount_percentage(self):
        return self.percentage / 100


class Claim(models.Model):
    CLAIM_STATUS = [
        ('PENDING', 'Чакаща'),
        ('APPROVED', 'Одобрена'),
        ('REJECTED', 'Отхвърлена'),
    ]

    policy = models.ForeignKey(InsurancePolicy, on_delete=models.CASCADE)
    claim_date = models.DateTimeField(auto_now_add=True)
    description = models.TextField()
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=10, choices=CLAIM_STATUS, default='PENDING')
    photos = models.ImageField(upload_to='claims/', blank=True)

    def __str__(self):
        return f"Claim #{self.id} - {self.policy.policy_number}"

templates/base.html
{% load static %}
{% load custom_filters %}

<!DOCTYPE html>
<html lang="en">
<!-- Starts Head Section -->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Застрахователна компания</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
    <style>
        .form-control[type="file"] {
            padding: 0.375rem 0.75rem;
            border: 1px solid #ced4da;
            border-radius: 0.375rem;
            background-color: #fff;
        }
        
        .form-control[type="file"]:focus {
            border-color: #86b7fe;
            box-shadow: 0 0 0 0.25rem rgba(13, 110, 253, 0.25);
        }
        
        .error {
            color: #dc3545;
            font-size: 0.875rem;
            margin-top: 0.25rem;
        }
        
        .label-input {
            margin-bottom: 1rem;
        }
        
        .label-input label {
            display: block;
            margin-bottom: 0.5rem;
        }
    </style>
</head>
<!-- End Head Section -->

<!-- Starts Body Section -->
<body>


<!-- Starts Header Section with Navigation Bar -->
<header style="
    position: fixed;
    top: 0;
    width: 100%;
    z-index: 1000;
    background: #8395ff;
    box-shadow: 0 2px 5px rgba(0,0,0,0.1);
    padding: 15px 0;">
    <nav class="navbar">
        <div class="container" style="
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin: 0 auto;
            padding: 0 20px;">
            <div class="logo">

                <!-- Link to Home Page -->
                <a class="home" href='{% url 'home' %}' style="
                text-decoration: none;
                color: #333;
                font-weight: bold;
                font-size: 1.2rem;">
                    <i>Застрахователна компания</i>
                </a>
            </div>

            <div class="nav-links">
                <ul class="nav-group" style="
                    display: flex;
                    list-style: none;
                    gap: 20px;
                    align-items: center;">
                    <li class="nav-item">
                        <!-- Link to About Page -->
                        <a href="{% url 'about' %}" class="nav-link" style="
                    text-decoration: none;
                    color: white;
                    font-weight: bold;
                    font-size: large;
                    transition: all 0.3s ease;">
                            <i>За нас</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <!-- Link to Contacts Page -->
                        <a href="{% url 'contact' %}" style="
                        text-decoration: none;
                        color: white;
                        font-weight: bold;
                        font-size: large;
                        transition: all 0.3s ease;">
                            <i>Контакти</i>
                        </a>
                    </li>

                    {% if not request.user.is_authenticated %}
                        <li class="nav-item">
                            <!-- Link to Login Page -->
                            <a href="{% url 'login' %}" style="
                                text-decoration: none;
                                color: white;
                                font-weight: bold;
                                font-size: large;
                                transition: all 0.3s ease;">
                                <i>Влез в профил</i>
                            </a>
                        </li>
                        <li class="nav-item">

                            <!-- Link to Register Page -->
                            <a href="{% url 'register' %}" style="
                                text-decoration: none;
                                color: white;
                                font-weight: bold;
                                font-size: large;
                                transition: all 0.3s ease;">
                                <i>Регистрация</i>
                            </a>
                        </li>
                    {% else %}

                        <li class="nav-item">
                            <!-- Link to Profile Page -->
                            <a href="{% url 'profile_details' request.user.pk %}" style="
                                text-decoration: none;
                                color: white;
                                font-weight: bold;
                                font-size: large;
                                transition: all 0.3s ease;">
                                <i>Профил</i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <!-- Link to Policies Page -->
                            <a href="{% url 'policy_list' %}" style="
                                text-decoration: none;
                                color: white;
                                font-weight: bold;
                                font-size: large;
                                transition: all 0.3s ease;">
                                <i>Полици</i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <!-- Link to Offers Page -->
                            <a href="{% url 'offer_list' %}" style="
                                text-decoration: none;
                                color: white;
                                font-weight: bold;
                                font-size: large;
                                transition: all 0.3s ease;">
                                <i>Оферти</i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <!-- Link to Claims Page -->
                            <a href="{% url 'claim_list' %}" style="
                                text-decoration: none;
                                color: white;
                                font-weight: bold;
                                font-size: large;
                                transition: all 0.3s ease;">
                                <i>Щети</i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <!-- Link to Cars Page -->
                            <a href="{% url 'car_list' %}" style="
                                text-decoration: none;
                                color: white;
                                font-weight: bold;
                                font-size: large;
                                transition: all 0.3s ease;">
                                <i>Автомобили</i>
                            </a>
                        </li>
						{% if user.is_staff %}
                        <li class="nav-item">
                            <!-- Link to Discounts Page -->
                            <a href="{% url 'discount_list' %}" style="
                                text-decoration: none;
                                color: white;
                                font-weight: bold;
                                font-size: large;
                                transition: all 0.3s ease;">
                                <i>Отстъпки</i>
                            </a>
                        </li>
						{% endif %}
                        <form method="post" action="{% url 'logout' %}">
                            {% csrf_token %}
                            <button class="btn" style="
                                color: white;
                                font-weight: bold;
                                font-size: large;
                                background: #3e4bff"
                                    type="submit"><i>Излез</i></button>
                        </form>

                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>
<!-- End Header Section with Navigation Bar -->

<!-- Starts Main Section -->
<main>
    <div class="container" style="
        padding-top: 120px;
        align-items: center;
        margin-bottom: 80px">

        {% block content %}

        {% endblock %}
    </div>
</main>
<!-- End Main Section -->

<!-- Start Footer Section -->
<div class="footer" style="
    position: fixed;
    bottom: 0;
    width: 100%;
    z-index: 1000;
    background: #b7cbff;
    padding: 10px 0;
    text-align: center;">
		<span class=" footer-section">
            © 2025 SOFTUNI Django Advanced Project by Sanya Lyubenova
        </span>
</div>
<!-- End Footer Section -->

</body>
</html>